---
- name: Deploy DANJR Backend
  hosts: danjr
  become: yes

  vars:
    app_dir: /home/ubuntu/danjr
    repo_url: https://github.com/jetweedy/danjr-backend.git  # <-- update this!

  tasks:
    - name: Update apt and install required packages
      apt:
        name:
          - git
          - python3-pip
          - python3-venv
        update_cache: yes

    - name: Clone the DANJR repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes

    - name: Set up Python virtual environment
      args:
        chdir: "{{ app_dir }}"
        creates: "venv"
      command: python3 -m venv venv

    - name: Install Python dependencies
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ app_dir }}/venv"

    - name: Run Django migrations
      command: "{{ app_dir }}/venv/bin/python manage.py migrate"
      args:
        chdir: "{{ app_dir }}"

    - name: Check if db.sqlite3 exists
      stat:
        path: "{{ app_dir }}/db.sqlite3"
      register: dbfile

    - name: Ensure correct permissions on db.sqlite3
      file:
        path: "{{ app_dir }}/db.sqlite3"
        owner: ubuntu
        group: ubuntu
        mode: '0664'
      when: dbfile.stat.exists

    - name: Ensure correct permissions on project directory
      file:
        path: "{{ app_dir }}"
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Upload .env file
      copy:
        src: .env
        dest: "{{ app_dir }}/.env"
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Copy systemd service file
      template:
        src: danjr-backend.service.j2
        dest: /etc/systemd/system/danjr-backend.service
      notify: Restart danjr backend

    - name: Enable danjr backend service
      systemd:
        name: danjr-backend
        enabled: yes
        state: started




  handlers:
    - name: Restart danjr backend
      systemd:
        name: danjr-backend
        state: restarted
